[project]
name = "ralph"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "open-interpreter>=0.4.3",
    "tiktoken>=0.7.0,<0.8.0",
]
